//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP463_ExpertSysProj {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FACT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FACT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CP463_ExpertSysProj.FACT", typeof(FACT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is advance package.
        /// </summary>
        internal static string advanceCon {
            get {
                return ResourceManager.GetString("advanceCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your website is have more than 500 connection per day ?.
        /// </summary>
        internal static string bandwidthQ {
            get {
                return ResourceManager.GetString("bandwidthQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is basic package.
        /// </summary>
        internal static string basicCon {
            get {
                return ResourceManager.GetString("basicCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your company like a big company (such as CP, BEER CHAING) ?.
        /// </summary>
        internal static string bigCompanyQ {
            get {
                return ResourceManager.GetString("bigCompanyQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is business pro package.
        /// </summary>
        internal static string businessProCon {
            get {
                return ResourceManager.GetString("businessProCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use a Dedicate IP ?.
        /// </summary>
        internal static string dedicateIPQ {
            get {
                return ResourceManager.GetString("dedicateIPQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is dedicate server (Call support for more detail).
        /// </summary>
        internal static string dedicateServerCon {
            get {
                return ResourceManager.GetString("dedicateServerCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you design for E-Commerce or Big community like webboard ?.
        /// </summary>
        internal static string eCommerceQ {
            get {
                return ResourceManager.GetString("eCommerceQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to regis a free domain ?.
        /// </summary>
        internal static string freeDomainRegisQ {
            get {
                return ResourceManager.GetString("freeDomainRegisQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you already have a domain name ?.
        /// </summary>
        internal static string haveDomainNameQ {
            get {
                return ResourceManager.GetString("haveDomainNameQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your work using heavy hardware ?.
        /// </summary>
        internal static string heavyUseQ {
            get {
                return ResourceManager.GetString("heavyUseQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which language that you want to make your own websie ?.
        /// </summary>
        internal static string langQ {
            get {
                return ResourceManager.GetString("langQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to manage anything (Such as Install web server, Email Server ETC.) ?.
        /// </summary>
        internal static string manageQ {
            get {
                return ResourceManager.GetString("manageQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is no suitible package.
        /// </summary>
        internal static string noCon {
            get {
                return ResourceManager.GetString("noCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is professional package.
        /// </summary>
        internal static string professionalCon {
            get {
                return ResourceManager.GetString("professionalCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you design for simple blog or SME webpage ?.
        /// </summary>
        internal static string simpleUsageQ {
            get {
                return ResourceManager.GetString("simpleUsageQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is standard package.
        /// </summary>
        internal static string standardCon {
            get {
                return ResourceManager.GetString("standardCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your website is a static web ?.
        /// </summary>
        internal static string staticWebQ {
            get {
                return ResourceManager.GetString("staticWebQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your website is have 3GB space in one or two year ?.
        /// </summary>
        internal static string threeGBspaceQ {
            get {
                return ResourceManager.GetString("threeGBspaceQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is untimate package.
        /// </summary>
        internal static string untimateCon {
            get {
                return ResourceManager.GetString("untimateCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is VPS Linux package.
        /// </summary>
        internal static string vpsLinuxCon {
            get {
                return ResourceManager.GetString("vpsLinuxCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My suggestion is VPS windows package.
        /// </summary>
        internal static string vpsMSCon {
            get {
                return ResourceManager.GetString("vpsMSCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which operation system that you want to use ?.
        /// </summary>
        internal static string vpsQ {
            get {
                return ResourceManager.GetString("vpsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Host package suggestion Expert System..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
